### ISSUE TITLE
2つ目のテスト"metadata is set"が実行完了しない

### ISSUE THREAD

**Issue by uukait** [unchain-tech/ETH-DAO#17]
![Screenshot 2023-11-16 at 16 05 00](https://github.com/unchain-tech/ETH-DAO/assets/60546319/26a6e063-423e-498c-9df7-0e3ee1965cd2)

**Comment by uukait** [comment]
ローカル環境でUNCHAIN-test-submissionsを実行した時のログ

```bash
▶ ETH-DAO test
  ✔ sdk is working (3.874125ms)
  ✖ metadata is set (480066.961875ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ NFT is minted (0.260167ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ NFT condition is set (0.416083ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ token contract is deployed (0.27075ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ token is minted (0.122125ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ token is transfered (0.121334ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ vote contract has right info (0.324291ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ vote contract has as 9 times much tokens as owner has (0.218958ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ vote contract has proposal (0.253875ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

  ✖ token role is passed to contract (0.114125ms)
    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
        at Logger.makeError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at JsonRpcProvider.<anonymous> (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
        at step (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
        at Object.throw (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
        at rejected (/Users/yukasaito/Desktop/git/unchain/UNCHAIN-test-submissions/submission/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) {
      reason: 'could not detect network',
      code: 'NETWORK_ERROR',
      event: 'noNetwork'
    }

▶ ETH-DAO test (480083.713459ms)


```

**Comment by uukait** [comment]
CI：
https://github.com/unchain-tech/ETH-DAO/actions/runs/6887162016/job/18733974425
